# Generated by Django 4.0.6 on 2022-07-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orginial_price',
            new_name='originial_price',
        ),
    ]
