# Generated by Django 4.0.6 on 2022-07-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_rename_orginial_price_product_originial_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='originial_price',
            new_name='original_price',
        ),
    ]
