# Generated by Django 4.0.6 on 2022-08-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_order_message_alter_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('運送中', '運送中'), ('完成', '完成')], default='運送中', max_length=150),
        ),
    ]
