# Generated by Django 4.0.6 on 2022-08-03 06:44

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile.jpg', null=True, upload_to=mainapp.models.get_profile_file_path),
        ),
    ]
